### ISSUE TITLE
Adding tutorials and other bits from user forums

### ISSUE THREAD

**Issue by ssiemon** [getsolus/help-center-docs#232]
Dear all,

i work as a technical writer in germany and i am an avid Solus user. While reading the forums, i found out that there are many tutorials and hints in the forums. 

What do you think of adding some of these things to the User Documentation?

Some examples:

- [Issues with upgrade / update-repo](https://discuss.getsol.us/d/1617-issue-with-eopkg-upgrade-update-repo)
- [How to stop Solus from collecting shared printers in the network](https://discuss.getsol.us/d/1617-issue-with-eopkg-upgrade-update-repo)

Scanning forums would lead to some more posts which may be useful for allot of users.

Would be glad to contribute to Solus.

Best wishes

**Comment by JoshStrobl** [comment]
The issue you referenced for eopkg 416 should only be temporary once we have the CDN in front of the repo again, and your link regarding shared printers go to the same URL as the eopkg one.

Generally speaking, no I don't think we need tutorials on the Help Center. That's why we have the Tutorials section on the forum.
