### ISSUE TITLE
Which version of markdown is used in the documentation?

### ISSUE THREAD

**Issue by xahodo** [getsolus/help-center-docs#316]
The README.md does not specify which version of markdown is used in the Solus documentation. This could cause issues for people trying to figure out what is and is not supported.

Github markdown, for example, is quite different from standard markdown.

**Comment by Staudey** [comment]
Currently, if I'm not mistaken, it should conform to the Hugo markdown parser https://www.markdownguide.org/tools/hugo/

"By default, Hugo uses the [Goldmark](https://github.com/yuin/goldmark/) Markdown processor which is fully CommonMark-compliant"

So that ^^

To be honest I've always just oriented myself on the existing documents. Also we probably don't want to put anything fancier than headings, images, code blocks and the like into our documentation. Keep it simple.

**Comment by DataDrake** [comment]
What @Staudey said is correct, so I'm going to go ahead and mark this as resolved.
